services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=lab3
    volumes:
      - mysql:/var/lib/mysql
      - ./lab3.sql:/docker-entrypoint-initdb.d/lab3.sql
    ports:
      - "13306:3306"
    networks:
      app:
        aliases:
          - db
          - mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    networks:
      - app
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    depends_on:
      - app


  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app

networks:
  app:

volumes:
  db_data: